
add_newline = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = 'âŒœ[$user]($style)âŒŸ'
disabled = true
show_always = false

[directory]
format = 'âŒœ[($path)]($style)âŒŸ'
truncation_length = 1
truncation_symbol = '../'

[aws]
format = 'âŒœ[$symbol($profile)(\($region\))(âŒœ$durationâŒŸ)]($style)âŒŸ'

[bun]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[c]
format = 'âŒœ[$symbol($version(-$name))]($style)âŒŸ'

[character]
format = """
[ã“ã“â‰» ](bold cyan)
"""

[cmake]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[cmd_duration]
format = 'âŒœ[â± $duration]($style)âŒŸ'

[cobol]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[conda]
format = 'âŒœ[$symbol$environment]($style)âŒŸ'

[crystal]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[daml]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[dart]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[deno]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[docker_context]
format = 'âŒœ[$symbol$context]($style)âŒŸ'

[dotnet]
format = 'âŒœ[$symbol($version)(ğŸ¯ $tfm)]($style)âŒŸ'

[elixir]
format = 'âŒœ[$symbol($version \(OTP $otp_version\))]($style)âŒŸ'

[elm]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[erlang]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[gcloud]
format = 'âŒœ[$symbol$account(@$domain)(\($region\))]($style)âŒŸ'

[git_branch]
format = 'âŒœ[$symbol$branch]($style)âŒŸ'

[git_status]
format = '([âŒœ$all_status$ahead_behindâŒŸ]($style))'

[golang]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[guix_shell]
format = 'âŒœ[$symbol]($style)âŒŸ'

[haskell]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[haxe]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[helm]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[hg_branch]
format = 'âŒœ[$symbol$branch]($style)âŒŸ'

[java]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[julia]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[kotlin]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[kubernetes]
format = 'âŒœ[$symbol$context( \($namespace\))]($style)âŒŸ'

[lua]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[memory_usage]
format = 'âŒœ$symbol[$ram( | $swap)]($style)âŒŸ'

[meson]
format = 'âŒœ[$symbol$project]($style)âŒŸ'

[nim]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[nix_shell]
format = 'âŒœ[$symbol$state( \($name\))]($style)âŒŸ'

[nodejs]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[ocaml]
format = 'âŒœ[$symbol($version)(\($switch_indicator$switch_name\))]($style)âŒŸ'

[opa]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[openstack]
format = 'âŒœ[$symbol$cloud(\($project\))]($style)âŒŸ'

[os]
format = 'âŒœ[$symbol]($style)âŒŸ'

[package]
format = 'âŒœ[$symbol$version]($style)âŒŸ'

[perl]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[php]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[pulumi]
format = 'âŒœ[$symbol$stack]($style)âŒŸ'

[purescript]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[python]
format = 'âŒœ[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)âŒŸ'

[raku]
format = 'âŒœ[$symbol($version-$vm_version)]($style)âŒŸ'

[red]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[ruby]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[rust]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[scala]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[spack]
format = 'âŒœ[$symbol$environment]($style)âŒŸ'

[sudo]
format = 'âŒœ[as $symbol]âŒŸ'

[swift]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[terraform]
format = 'âŒœ[$symbol$workspace]($style)âŒŸ'

[time]
disabled = false
format = '[$time]($style) â–‰ '
time_format = '%R'

[vagrant]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[vlang]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

[zig]
format = 'âŒœ[$symbol($version)]($style)âŒŸ'

